# Generated by Django 4.2.5 on 2023-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_downvotes_downvote_rename_upvotes_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.TextField(default=''),
        ),
    ]
