# Generated by Django 4.2.5 on 2023-09-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
