# Generated by Django 4.2.5 on 2023-09-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
