# Generated by Django 4.2.5 on 2023-09-24 19:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
