# Generated by Django 4.2.5 on 2023-09-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_answer_details_alter_question_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='details',
            field=models.TextField(),
        ),
    ]
